export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const GET_MEDICHINES = "GET_MEDICHINES";
export const DELETE_MEDICHINES = "DELETE_MEDICHINES";
export const ADD_MEDICHINES = "ADD_MEDICHINES";
export const UPDATE_MEDICHINES = "UPDATE_MEDICHINES";
export const LOADING_MEDICHINES = "LOADING_MEDICHINES";

export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";

