export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const GET_MEDICHINES = "GET_MEDICHINES";
export const DELETE_MEDICHINES = "DELETE_MEDICHINES";