export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const GET_MEDICHINES = "GET_MEDICHINES";
export const DELETE_MEDICHINES = "DELETE_MEDICHINES";
export const ADD_MEDICHINES = "ADD_MEDICHINES";
export const UPDATE_MEDICHINES = "UPDATE_MEDICHINES";
export const LOADING_MEDICHINES = "LOADING_MEDICHINES";
export const ERROR_MEDICHINES = "ERROR_MEDICHINES";

export const ADD_TO_CART = "ADD_TO_CART";
export const INC_CART = "INC_CART";
export const DEC_CART = "DEC_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";


export const GET_DOCTORS= "GET_DOCTORS";
export const DELETE_DOCTORS= "DELETE_DOCTORS";
export const ADD_DOCTORS= "ADD_DOCTORS";
export const UPDATE_DOCTORS= "UPDATE_DOCTORS";
export const LOADING_DOCTORS= "LOADING_DOCTORS";
export const ERROR_DOCTORS = "ERROR_DOCTORS";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";

export const FORGOT_REQUEST = "FORGOT_REQUEST";
export const FORGOT_RESPONSE = "FORGOT_RESPONSE";


export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";





